### ISSUE TITLE
Request failure from controller should be handled

### ISSUE THREAD

**Issue by cqbqdd11519** [jwkim1993/approval-operator#30]
## Expected Behavior
- In some cases, such as where watcher pod is dead or some kind of network failure situation, http request from controller to watcher pod might fail
- The failures should be handled in some ways

## Current Behavior
- Timeout occurs infinitely until the request succeeds, or until Approval is deleted

### Exponential Backoff
- We can adopt exponential backoff strategy, where the gap between the retries grows exponentially.
- Also, we can set `maxRetry` (maybe a constant or an env. variable) and if the retry counter exceeds the max value, we can just mark the Approval `Failed` and don't care any more.
- We already have `retry` counter in status field. This value can be useful.

**Comment by jwkim1993** [comment]
sleep을 일정 시간 주고 다시 시도하는게 좋을까요??

**Comment by cqbqdd11519** [comment]
sleep이면 스레드를 계속 먹고있으니 안될것같고, 제가 생각한 방식은 아래 라인에서
https://github.com/jwkim1993/approval-operator/blob/ecee27a5e807c915f902c85b0ab8123801feda7d/pkg/controller/approval/approval_controller.go#L142
 reconcile.Result에 RequeAfter 필드를 줘서 나중에 다시 요청 들어오는 방식을 생각했어요

https://sdk.operatorframework.io/docs/golang/quickstart/#reconcile-loop
